server:
  port: 8090

#Metrics related configurations
management:
  #  See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html, https://www.baeldung.com/spring-boot-actuators for details
  endpoints.web.exposure.include: "*"
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  metrics:
    export.prometheus.enabled: true
    tags:
      environment: development

logging:
  level:
    org.zalando.logbook: TRACE

# https://github.com/zalando/logbook
logbook:
  exclude:
    - "/actuator/**"
    - "/swagger-ui/**"
    - "/api-docs/**"
  filter.enabled: true
  secure-filter.enabled: true
  obfuscate:
    headers:
      - Token
    parameters:
      - password
      - authCode
  write:
    max-body-size: 1000
  format:
    style: http
