backend:
  hello-world-target: "QA"

#Metrics related configurations
management:
  metrics:
    tags:
      environment: qa
    export.cloudwatch:
      enabled: true
      namespace: spring-boot-template-qa
