image: docker.inventale.com/platform/build/jdk11:1.0.1

stages:
  - verify

before_script:
#  cache gradle for the branch
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: one-key-to-rule-them-all
  paths:
    - .gradle/wrapper
    - .gradle/caches

# --------- Verify stage ---------
tests:
  stage: verify
  script:
    - ./gradlew clean test --build-cache --scan
  except:
    - schedules
    - tags
  artifacts:
    expire_in: 2 weeks
    when: always
    name: "$CI_BUILD_ID"
    paths:
      - $CI_PROJECT_DIR/**/build/reports/*
    reports:
      junit: $CI_PROJECT_DIR/**/build/test-results/test/TEST-*.xml
