image: docker.inventale.com/platform/build/jdk/jdk11:1.1.0

stages:
  - verify

before_script:
#  cache gradle for the branch
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  key: your-project-one-key-to-rule-them-all
  paths:
    - .gradle/wrapper
    - .gradle/caches

# --------- Verify stage ---------
tests:
  stage: verify
  script:
    - ./gradlew clean test --build-cache --scan
  except:
    - schedules
    - tags
  artifacts:
    expire_in: 2 weeks
    when: always
    name: "$CI_BUILD_ID"
    paths:
      - $CI_PROJECT_DIR/**/build/reports/*
    reports:
      junit: $CI_PROJECT_DIR/**/build/test-results/test/TEST-*.xml

it:
  stage: verify
  script:
    - ./gradlew -PfunctionalTests=true check
  artifacts:
    expire_in: 2 weeks
    when: always
    name: "$CI_BUILD_ID"
    paths:
      - $CI_PROJECT_DIR/**/build/*
    reports:
      junit: $CI_PROJECT_DIR/**/build/test-results/test/TEST-*.xml
  only:
    variables:
      - $RUN_IT

owasp:
  stage: verify
  script:
    - ./gradlew dependencyCheckAnalyze
  except:
    - schedules
    - tags
  artifacts:
    expire_in: 2 weeks
    when: always
    name: "$CI_BUILD_ID"
    paths:
      - $CI_PROJECT_DIR/**/build/reports/*
    reports:
      junit: $CI_PROJECT_DIR/**/build/test-results/test/TEST-*.xml
